/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.xw218.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Random;

/**
 * App class for the whole program
 */
public class App {
  // public String getGreeting() { return "Hello World!"; }
  /**
   * Main function
   */
  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V2ShipFactory();
    // let user choose the role for the player

    //Player p1 = new TextPlayer("A", b1, input, System.out, factory);
    //Player p2 = new TextPlayer("B", b2, input, System.out, factory);
    Player p1, p2;
    //App app = new App(p1, p2);
    App app = new App(input);
    if(app.chooseRole("Do you want Player A computer or human?")){
       p1 = new TextPlayer("A", b1, input, System.out, factory);
    }else{
      Random r1 = new Random(1);
      p1 = new ComputerPlayer("A", b1, System.out, factory, r1);
    }
    if(app.chooseRole("Do you want Player B computer or human?")){
       p2 = new TextPlayer("B", b2, input, System.out, factory);
    }else{
       Random r2 = new Random(2);
      p2 = new ComputerPlayer("B", b2, System.out, factory, r2);
    }
    app.setPlayers(p1, p2);
    app.doPlacementPhase();
    while (app.doAttackingPhase()) {
      continue;
    }
  }

  BufferedReader input;
  Player player1;
  Player player2;

  /**
   * Constructor
   */
  /*  public App(Player p1, Player p2) {
    this.player1 = p1;
    this.player2 = p2;
    }*/

  public void setPlayers(Player p1, Player p2){
    this.player1 = p1;
    this.player2 = p2;
  }

  public boolean chooseRole(String prompt) throws IOException{
    while (true) {
      System.out.println(prompt);
      String s = input.readLine().toUpperCase();
      if ((s.equals("COMPUTER"))) {
        return false;
      } else if (s.equals("HUMAN")) {
        return true;
      } else {
        System.out.println("Please enter human or computer");
      }
    }
  }

  public App(BufferedReader input) {
    // need to choose the player
    this.input = input;
  }

  /**
   * Place 10 ships for each player
   */
  public void doPlacementPhase() throws IOException {
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public boolean doAttackingPhase() throws IOException {
    if (player1.playOneTurn(player2.getBoard(), player2.getView()) == false) {
      return false;
    }
    if (player2.playOneTurn(player1.getBoard(), player1.getView()) == false) {
      return false;
    }
    return true;
  }
}
